---

# Copyright 2021 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-dispatcher-cluster
  namespace: knative-eventing
data:
  _example: |
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################
    # This block is not actually functional configuration,
    # but serves to illustrate the available configuration
    # options and document them in a way that is accessible
    # to users that `kubectl edit` this config map.
    #
    # These sample configuration options may be copied out of
    # this example block and unindented to be in the data block
    # to actually change the configuration.
    #
    # membership.strategy indicates which strategy to use to detect cluster membership changes.
    #
    # Supported values: "dns"
    membership.strategy: "dns"

    # dns.record indicates the DNS A record to use to detect cluster membership changes.
    #
    # The value must be a fully qualified domain name with a dot at the end, including the Kubernetes cluster domain
    # suffix.
    #
    # It's only used when membership.strategy is equal to "dns".
    dns.record: "kafka-broker-dispatcher-cluster.knative-eventing.svc.cluster.local."

    # dns.poll.ms indicates the polling interval to detect cluster membership changes.
    #
    # Note: while a small number detects faster cluster membership changes, it might overload your DNS servers.
    #
    # It's only used when membership.strategy is equal to "dns".
    dns.poll.ms: "60000"
