resources:
  - ../receiver
  - ../dispatcher

patches:
  - target:
      group: apps
      kind: Deployment
      name: kafka-receiver
    path: receiver-deployment-patch.yaml
  - target:
      kind: Service
      name: kafka-ingress
    path: receiver-svc-patch.yaml

images:
  - name: knative-kafka-receiver
    newName: ${KNATIVE_KAFKA_RECEIVER_IMAGE}
  - name: knative-kafka-dispatcher
    newName: ${KNATIVE_KAFKA_DISPATCHER_IMAGE}
