- op: replace
  path: /metadata/name
  value: kafka-channel-ingress
- op: replace
  path: /metadata/labels/app
  value: kafka-channel-receiver
- op: replace
  path: /spec/selector/app
  value: kafka-channel-receiver
