{
 "title": "General",
 "description": "Knative Eventing Kafka",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace_name",
    "query": {
     "query": "label_values(event_count_1_total, namespace_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Receiver - Global Failure Status Codes Rate",
   "type": "timeseries",
   "description": "Receiver - Failure Status Codes Rate",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job, code) (rate(vertx_http_server_requests_total{namespace=\"knative-eventing\", code=~\"4.*|5.*\", method=\"POST\"}[5m]))",
     "legendFormat": "{{job}} ({{code}})"
    }
   ]
  },
  {
   "title": "Receiver - Global Event Dispatch Latency",
   "type": "timeseries",
   "description": "Knative Eventing Kafka Ingress - event dispatch latency (p99)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(event_dispatch_latencies_ms_bucket{job=\"kafka-broker-ingress\", namespace=\"knative-eventing\"}[5m])) by (le))",
     "legendFormat": "kafka-broker-ingress"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(event_dispatch_latencies_ms_bucket{job=\"kafka-sink-ingress\", namespace=\"knative-eventing\"}[5m])) by (le))",
     "legendFormat": "kafka-sink-ingress"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(event_dispatch_latencies_ms_bucket{job=\"kafka-channel-ingress\", namespace=\"knative-eventing\"}[5m])) by (le))",
     "legendFormat": "kafka-channel-ingress"
    }
   ]
  },
  {
   "title": "Receiver - Success Status Codes Rate ($namespace_name)",
   "type": "timeseries",
   "description": "Receiver - Success Status Codes Rate (2xx)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (job) (rate(event_count_1_total{response_code_class=\"2xx\", namespace=\"knative-eventing\", namespace_name=~\"$namespace_name\"}[5m]))",
     "legendFormat": "{{job}} "
    }
   ]
  },
  {
   "title": "Receiver - Event Types ($namespace_name)",
   "type": "table",
   "description": "Knative Eventing Kafka - Event Types",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (name, namespace_name, event_type, job) (event_count_1_total{namespace=\"knative-eventing\", namespace_name=~\"$namespace_name\"})",
     "legendFormat": "kafka-broker-ingress"
    }
   ]
  }
 ]
}